### ISSUE TITLE
Reading CFG files

### ISSUE THREAD

**Issue by hari-ushankar** [eisenforschung/magnesium-mtp-training-data#1]
Hi,

I was hoping how does one read the CFG files from your data (Everything.cfg for example) in pyiron or in ASE?

I seem to get the following error while using ASE to read the structures:
`ValueError: could not convert string to float: 'BEGIN_CFG'`

my code:

```
from ase.io import read

atoms = read('Everything.cfg',format='cfg')
``` 

EDIT: Also would be nice to visualise these structures; OVITO seems to have a problem with that.

**Comment by jan-janssen** [comment]
@hari-ushankar the CFG files are created by the Moment Tensor Potential (MTP) fitting code developed by Alexander Shapeev https://gitlab.com/ashapeev a reader of these files is available as part of the pyiron package at https://github.com/pyiron/pyiron_contrib/blob/main/pyiron_contrib/atomistics/mlip/cfgs.py

**Comment by hari-ushankar** [comment]
Hi @jan-janssen , 
Thank you for this! 

I was able to successfully load the cfg file using `pyiron_contrib.atomistics.mlip.cfgs.load_cfgs()'; but unfortunately there is no plot3d() that I can use to view it inside NGLview in Jupyter notebook. Is there a way to dump out a XYZ file and use OVITO to see the various configurations?
I just want to get sense of how different supercells are arranged to get different local atomic environments for Mg to parameterize a MTP. 

@pmrv , maybe you have some pointers?
here is the CFG compressed into a zip. [Everything.zip](https://github.com/eisenforschung/magnesium-mtp-training-data/files/11402439/Everything.zip)

EDIT: to be more specific, this is what I had done:

![image](https://user-images.githubusercontent.com/71093689/236354528-1656d4df-5298-4e63-9c22-1e1d92e28930.png)

**Comment by pmrv** [comment]
Sorry for the delay (somehow the notifications were disabled for this repo). 

The cfg files and the parser @jan-janssen mentioned are MTP specific and the objects that you get by reading them are not full `Atoms` objects.  That's why 3D plotting and writing them doesn't work.  If you just want to look at the structures it'll be easier to use the training data containers that are in the exported pyiron projects.  You can do something like

```python
structure_pr = Project('structures')
j = structure_pr.load('Hydro')
structure = j.get_structure(0)
structure.plot3d()
structure.write('structure_0.xyz') # <- this you can read with ovito
```

Or is there a problem with importing the projects?

**Comment by hari-ushankar** [comment]
Hi @pmrv , this makes a lot of sense now to me! and thank you @jan-janssen for pointing me in the right direction.

And yes, I'm not 100% sure how to import the projects. All I see are .tar.gz files in the [Edmond file repo](https://edmond.mpdl.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.A3MB7Z).

What I have done right now is: I have unpacked the `structure_packed` dir and tried to execute the above code:

```
structure_pr = Project('structures_packed/structures/')
j = structure_pr.load('Hydro')
```

and I get the following warning:

```
2023-05-06 11:42:32,758 - pyiron_log - WARNING - Job 'Hydro' does not exist and cannot be loaded
2023-05-06 11:42:32,758 - pyiron_log - WARNING - Job 'Hydro' does not exist and cannot be loaded
```

Maybe am I missing something basic here?

**Comment by pmrv** [comment]
Ah, just unpacking the tarballs is not enough to import the projects.  The `Unpack.ipynb` notebook has the code to do it.  Let me know if there's any errors there.

**Comment by hari-ushankar** [comment]
This is great! thank you for the inputs, @pmrv. I need inputs on a few more things:
(this issue may not be the right place to do this, please let me know if I need to move it elsewhere..)

(i) I have an older version of `pyiron` on my compute cluster. This version doesnt have separate `pyiron_atomistics`, `pyiron`, `pyiron_base`. I'm not sure how to update this. Do you recommend I remove the current repo and starting fresh? I don't have that many important jobs in that pyiron version, I suppose I can safely remove it.  

(ii) in your paper, you talk about a procedure to setup training sets, can this be done in pyiron?
it was VOLMIN-->CELLMIN-->INTMIN. I guess I haven't followed along with the docs in pyiron. can you point to a place where I can look this up?

**Comment by pmrv** [comment]
> This is great! thank you for the inputs, @pmrv. I need inputs on a few more things: (this issue may not be the right place to do this, please let me know if I need to move it elsewhere..)

It's ok here for now.

> (i) I have an older version of `pyiron` on my compute cluster. This version doesnt have separate `pyiron_atomistics`, `pyiron`, `pyiron_base`. I'm not sure how to update this. Do you recommend I remove the current repo and starting fresh? I don't have that many important jobs in that pyiron version, I suppose I can safely remove it.

Probably yes, there's a finite chance that we can still load old jobs anyway.  If you don't care about the old work at all, be sure to delete the database as well.  I'm guessing you are using the `sqlite`, so it's just a matter of checking your `.pyiron` for the filepath to the database and delete that.

> (ii) in your paper, you talk about a procedure to setup training sets, can this be done in pyiron? it was VOLMIN-->CELLMIN-->INTMIN. I guess I haven't followed along with the docs in pyiron. can you point to a place where I can look this up?

I don't have public code for this yet, but you can do this with the `Vasp` job, the `calc_minimize` method and modifying the `IBRION` tag of VASP (via `job.input.incar`). Sadly the doc web page is broken right now, so I can't point you to something immediately.

**Comment by pmrv** [comment]
There's some information on how to create structure databases in the latest workshop material: http://pyiron.org/potentials-workshop-2022/introduction/ex_02_creating_structure_databases.html#add-some-defect-structures-vacancies-surfaces-etc

**Comment by hari-ushankar** [comment]
Awesome, I can start from here. I'll maybe ping you via email or open an issue on pyiron_atomistics if need be (I hope that is ok with you)! Thanks again, @pmrv !
