### ISSUE TITLE
StructureContainer object has no attribute 'plot' & setting up LAMMPS jobs for structures in a structure container

### ISSUE THREAD

**Issue by hari-ushankar** [eisenforschung/magnesium-mtp-training-data#2]
Hello again :wave: ,

I'm now tinkering around with dataset by using one of the notebook provided- `RandSPGExample.ipynb`. Somehow after creating the randspg structure by using:

`spg = randspg(pr, np.arange(1,11), atomic_volume=12, min_radius=1.9, repetitions=1, element='Cu')`; I'm not able to visualize various structural properties such as Lattice vector lengths, angles, atomic volume and Density as shown for Mg. 

Am I missing something basic here? 

Also, I'm interested in testing the workflow in the published work of yours. As a first step, I try to use LAMMPS to iteratively relax from (i) VOLMIN to (ii) CELLMIN to (iii) INTMIN.

Can you check if the following does what I intend to do with (i)-->(ii)--(iii)?

For (i), this is what I have:
```
units 	metal 	
dimension 	3 	
boundary 	p p p 	
atom_style 	atomic 	
read_data 	structure.lmp 	
variable dumptime 	equal 1


include 	potential.inp 	
compute peratom all pe/atom 
fix             1 all box/relax iso 0.0 vmax 0.001
dump 1 	all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz
dump_modify 1 	sort id format line "%d %d %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g" 	
min_style cg
minimize 	1e-10 0. 100000 10000000

thermo_style 	custom step temp pe etotal pxx pxy pxz pyy pyz pzz vol 	
thermo_modify 	format float %20.15g
thermo 	100 	

```

For (ii), I have the following [I'm not sure if this is right; in reality I should box/relax xy 0.0 yz 0.0 xz 0.0; but if the box is orthogonal , LAMMPS throws an error according to https://docs.lammps.org/fix_box_relax.html] :
```
units 	metal 	
dimension 	3 	
boundary 	p p p 	
atom_style 	atomic 	
read_data 	structure.lmp 	
variable dumptime 	equal 1


include 	potential.inp 	
compute peratom all pe/atom 
fix             1 all box/relax aniso 0.0 vmax 0.001
dump 1 	all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz
dump_modify 1 	sort id format line "%d %d %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g" 	
min_style cg
minimize 	1e-10 0. 100000 10000000

thermo_style 	custom step temp pe etotal pxx pxy pxz pyy pyz pzz vol 	
thermo_modify 	format float %20.15g
thermo 	100 	
```

For (iii), I use something like this:
```
units 	metal 	
dimension 	3 	
boundary 	p p p 	
atom_style 	atomic 	
read_data 	structure.lmp 	
variable dumptime 	equal 1


include 	potential.inp 	
compute peratom all pe/atom 
dump 1 	all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz
dump_modify 1 	sort id format line "%d %d %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g" 	
min_style cg
minimize 	1e-10 1e-10 100000 10000000

thermo_style 	custom step temp pe etotal pxx pxy pxz pyy pyz pzz vol 	
thermo_modify 	format float %20.15g
thermo 	100 	
```

I'm not sure how to supply this inside pyiron as input to LAMMPS and minimize the structures in my container iteratively?
@pmrv , any ideas/pointers?

**Comment by hari-ushankar** [comment]
Ok, I did figure out what was the problem here, `spg` should be actually a container to visualize the cell properties.

the following code snippet worked fine for me:

```
container = pr.create.job.TrainingContainer('dataset_example')
for i in np.arange(2,spg.number_of_structures):
    job_lammps = pr.create.job.Lammps("lammps_job")
    job_lammps.structure = spg.structure_lst[int(i)]
    job_lammps.potential = job_lammps.list_potentials()[0]
    job_lammps.calc_minimize(pressure=0)
    job_lammps.run(delete_existing_job=True)
    container.include_job(job_lammps)
df = container.to_pandas()
df['energy_atom'] = (df.energy / df.number_of_atoms)
df['volume_atom'] = df.atoms.map(lambda s: s.get_volume(per_atom=True))
container.plot.cell()
sns.scatterplot(
    data=df,
    x='volume_atom',
    y='energy_atom'
)
plt.xlabel(r'Atomic Volume [$\mathrm{\AA}^3$/atom')
plt.ylabel(r'Atomic Energy [eV/atom]')
plt.legend(title='Mg')
```

Can you make clarify about the LAMMPS minimization steps for me, please?

Also, is there a way to export the above `container` as a .extxyz file for ACE training? I'm still using @cortner 's Julia code from here: https://github.com/ACEsuit.

**Comment by cortner** [comment]
Please check with ateemu which other formats we can import

**Comment by pmrv** [comment]
Hey,

there's no builtin write method, but you can quickly do it with something like

```python
cont = pr.load(...)
with open('structures.extxyz', 'w') as f: 
  for s in cont.iter_structures():
    s.write(f) # this is inherited from ASE, so pick any format that it supports
```

Feel free to submit a PR if that does it for you. ;)

As for the minimization, I am sadly mostly illiterate when it comes to lammps input scripts, but you can do it with the `calc_minimize` method:

(lammps)
```python
# VolMin
job.structure.add_tag(selective_dynamics=[False,False,False]) # freezes fractional coordinates of all atoms
job.calc_minimize(pressure=0)
# CelllMin
job.structure.add_tag(selective_dynamics=[False,False,False]) # freezes fractional coordinates of all atoms
job.calc_minimize(pressure=[0,0,0,0,0,0])
# IntMin
job.calc_minimize(pressure=[0,0,0,0,0,0])
```

for VASP the syntax is slightly different, but it is more easily achieved by the `ISIF` [flag](https://www.vasp.at/wiki/index.php/ISIF)
```python
# VolMin
job.calc_minimize(pressure=0.0, volume_only=True)
# CellMin
job.calc_minimize()
job.incar['ISIF'] = 5
# IntMin
job.calc_minimize(pressure=0.0)
```
you can check after calling these which `ISIF` pyiron picked by `job.input.incar`.

What I do is essentially iterating over the container from randspg and apply the volume minimization in one project.  Collect all structures from that with `TrainingContainer.include_job` or `StructureContainer.add_structure(job.get_structure())` and then repeat.

If your `StructureContainer` doesn't have a `plot` attribute, then your `pyiron_atomistics` is out of date.  If you install via conda and the problem persists after an update, you'll need to update the pyiron packages explicitly by providing the latest versions `conda install -c conda-forge pyiron_atomistics=...` (yes, it's a bit stupid, but such are the ways of the conda).
